### ISSUE TITLE
Component letters

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#11]
**Please describe the feature you want this project to offer**
Make a UI for the letters.

**Describe the solution you'd like**
The UI should look neat, clean and concise.

**Additional context (Optional)**
- Depends on #9

**Comment by tnmyk** [comment]
@aneeshpanda I would love to work on this but I think there are too many tests ... Can u help with those? Its really hard even to get it compiled 😅

**Comment by aneeshpanda** [comment]
> @aneeshpanda I would love to work on this but I think there are too many tests ... Can u help with those? Its really hard even to get it compiled 😅

@tnmyk, Could you please elaborate?

**Comment by thisispriyanshu** [comment]
I would like to take up this issue. Please assign it to me.
