### ISSUE TITLE
Status of clicked letters

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#16]
**Please describe the feature you want this project to offer**
The A-Z letters remain the same before and after clicking.

**Describe the solution you'd like**
Correct letter -> text-color - green
Wrong letter -> text-color - red

**Comment by Siddharth1002** [comment]
Can I work on this?

**Comment by Siddharth1002** [comment]
I would like to try this issue.

**Comment by Akshaya-vc** [comment]
I have assigned you this issue!
