### ISSUE TITLE
Create Logic to get a word

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#2]
**Please describe the feature you want this project to offer**
There are a few words in the helpers and each time the game starts, a random word is selected with it. 

**Describe the solution you'd like**
Import the Words from helpers, and randomly choose a word. 

**Additional context (Optional)**
Refer to how a random object is selected in JS.

**Comment by omriattiya** [comment]
Hi, I would like to add this feature :)

**Comment by precious-adeyinka** [comment]
Hey @aneeshpanda can you assign me after the countdown party please?
Thanks!

**Comment by aneeshpanda** [comment]
> Hi, I would like to add this feature. can you assign me?

Go ahead, I'm assigning this issue to you.
