### ISSUE TITLE
Add info about chances left

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#20]
**Please describe the feature you want this project to offer**
Currently chances left aren't displayed.

**Describe the solution you'd like**
Add info about chances left.

**Comment by MuhammadTanveer94** [comment]
@aneeshpanda can i do this?

**Comment by aneeshpanda** [comment]
> @aneeshpanda can i do this?

@MuhammadTanveer94 I'm assigning this issue to you!

**Comment by MuhammadTanveer94** [comment]
@aneeshpanda  is this empty project?

**Comment by aneeshpanda** [comment]
@MuhammadTanveer94 Yeah, it's an empty project for you guys to develop it.
