### ISSUE TITLE
Use Context APIs to have support for Dark and Light Theme

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#21]
**Please describe the feature you want this project to offer**
Only a singled Themed website.

**Describe the solution you'd like**
Add support to toggle between dark and light themes.

**Comment by MuhammadTanveer94** [comment]
@aneeshpanda i would love to contribute on this issue. Please assign me this issue.

**Comment by aneeshpanda** [comment]
Fine then, I'm assigning this issue to you!

**Comment by sreechand2002** [comment]
@aneeshpanda can I work on this as I see the previous contributor hasn't resolved it for a long time

**Comment by MuhammadTanveer94** [comment]
> @aneeshpanda can I work on this as I see the previous contributor hasn't resolved it for a long time

I am already working on it.

**Comment by MuhammadTanveer94** [comment]
@aneeshpanda Please look into this PR https://github.com/IEEE-VIT/hangman-react/pull/24

**Comment by MuhammadTanveer94** [comment]
> @aneeshpanda Please look into this PR #24

for reference 

![image](https://user-images.githubusercontent.com/43910948/135722648-b7f71931-9452-4c00-8959-eb4c31f2db1c.png)

![image](https://user-images.githubusercontent.com/43910948/135722653-753b29d9-24ea-4b37-9a39-5bcf730025dd.png)
