### ISSUE TITLE
Build failed after running npm start

### ISSUE THREAD

**Issue by akgupta0777** [IEEE-VIT/hangman-react#22]
# Bug Report

Bug: React build failed with errors related to ES-Lint.

## Description

After installing and setup.
On running npm start and visiting port 3000
Following error occurs
![image](https://user-images.githubusercontent.com/51379307/135712641-899ed50f-a862-499b-9dd4-e8905fc05771.png)

### Steps to Reproduce

1. Step 1 run npm install on your forked copy. 
2. Step 2 run npm start to trigger the development build.

### Expected Result

The app should function normally.

You may write the expected result or add a screenshot.

### Actual Results

Refer to the screenshot above.

also, https://hangman-react.pages.dev/ doesn't seems to work on visiting only header with hangman shows on screen.

**Comment by aneeshpanda** [comment]
> # Bug Report
> Bug: React build failed with errors related to ES-Lint.
> 
> ## Description
> After installing and setup. On running npm start and visiting port 3000 Following error occurs ![image](https://user-images.githubusercontent.com/51379307/135712641-899ed50f-a862-499b-9dd4-e8905fc05771.png)
> 
> ### Steps to Reproduce
> 1. Step 1 run npm install on your forked copy.
> 2. Step 2 run npm start to trigger the development build.
> 
> ### Expected Result
> The app should function normally.
> 
> You may write the expected result or add a screenshot.
> 
> ### Actual Results
> Refer to the screenshot above.
> 
> also, https://hangman-react.pages.dev/ doesn't seems to work on visiting only header with hangman shows on screen.

**Comment by aneeshpanda** [comment]
> # Bug Report
> Bug: React build failed with errors related to ES-Lint.
> 
> ## Description
> After installing and setup. On running npm start and visiting port 3000 Following error occurs ![image](https://user-images.githubusercontent.com/51379307/135712641-899ed50f-a862-499b-9dd4-e8905fc05771.png)
> 
> ### Steps to Reproduce
> 1. Step 1 run npm install on your forked copy.
> 2. Step 2 run npm start to trigger the development build.
> 
> ### Expected Result
> The app should function normally.
> 
> You may write the expected result or add a screenshot.
> 
> ### Actual Results
> Refer to the screenshot above.
> 
> also, https://hangman-react.pages.dev/ doesn't seems to work on visiting only header with hangman shows on screen.

Thank You for noticing this issue @akgupta0777. Would you like to take it up?

**Comment by sreechand2002** [comment]
Can you assign it to me?

**Comment by aneeshpanda** [comment]
> Can you assign it to me?

@sreechand2002 I'm assigning this issue to you.

**Comment by ankitgauri26** [comment]
@aneeshpanda - Can you please assign the issue to me. I have knowledge of what is causing this issue and how we can fix it.
