### ISSUE TITLE
Fix: Get Random Word Not Defined

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#25]
# Bug Report

Fix: Get Random Word Not Defined

## Description
![image](https://user-images.githubusercontent.com/71512843/135730009-77b8bfbd-813e-4675-8c56-ea061f02f965.png)

## Fix

Comment the useState

**Comment by rrithick116** [comment]
Hey bro i looked through the code ,i saw the getRandomWord() function commented , is that what i should try solving ??

**Comment by aneeshpanda** [comment]
> Hey bro i looked through the code ,i saw the getRandomWord() function commented , is that what i should try solving ??

Hey, @rrithick116! So currently what is happening is currentWord, getRandomWord is commented since they weren't being used, you currently only need to comment out the currentWord line for the site to work and others to start working on it.

**Comment by rrithick116** [comment]
Sure bro ,so can i start doing it ..

**Comment by aneeshpanda** [comment]
> Sure bro ,so can i start doing it ..

@rrithick116, I'm assigning this issue to you. Please fix this ASAP.
