### ISSUE TITLE
Logic to calculate winner

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#3]
**Please describe the feature you want this project to offer**
Add Logic for calculating winner in Helpers.js

**Describe the solution you'd like**
Make a function that checks the conditions of winning with the situation of the game

**Additional context (Optional)**
Refer to how a Hangman game works, and how it can be implemented using arrays in js.

**Comment by precious-adeyinka** [comment]
Hey @aneeshpanda can you assign me after the countdown party please?
Thanks!

**Comment by aneeshpanda** [comment]
> Hey @aneeshpanda can you assign me after the countdown party please? Thanks!

@precious-adeyinka Sorry for the delay, assigning you this issue.
