### ISSUE TITLE
Logic for letters

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#4]
**Please describe the feature you want this project to offer**
Add logic for letters in App.jsx

**Describe the solution you'd like**
A letter chosen, is either correct, wrong or remaining, maintain that in a state.

**Comment by AZIZXlaouiti** [comment]
hey can you  assign me this

**Comment by aneeshpanda** [comment]
> hey can you assign me this

Hi, @AZIZXlaouiti! Assigning this issue to you.
