### ISSUE TITLE
Logic for letter

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#5]
**Please describe the feature you want this project to offer**
Add Logic for using letter component in Letter.component.jsx

**Describe the solution you'd like**
Once a letter is clicked, change the state and update it.

**Comment by NicolasBiondini** [comment]
Hi! I would like to take care of this issue.

**Comment by aneeshpanda** [comment]
> Hi! I would like to take care of this issue.

Go ahead, I'm assigning this issue to you.

**Comment by NicolasBiondini** [comment]
I just made it. I send you the PR. Thank you!
