### ISSUE TITLE
Logic for Guessing

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#7]
**Please describe the feature you want this project to offer**
Add Logic for guessing the word in Guessing.component.jsx

**Describe the solution you'd like**
Display only the correct letters that are clicked, which will be passed from App.jsx.

**Comment by Muskan-sam** [comment]
hey @aneeshpanda I would like to contribute to this issue. Can you assign it to me , please?

**Comment by aneeshpanda** [comment]
> hey @aneeshpanda I would like to contribute to this issue. Can you assign it to me , please?

Hey @Muskan-sam! I'm assigning this issue to you!
