### ISSUE TITLE
Component letter

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#9]
**Please describe the feature you want this project to offer**
Make a UI for how the letter will be displayed in the Letters.component.jsx

**Describe the solution you'd like**
The letters should be separate and look defined.

**Comment by Khusyasy** [comment]
can i take a look at this issue?

**Comment by aneeshpanda** [comment]
> can i take a look at this issue?

Sure, @Khusyasy. Assigning this issue to you.
